### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by Vatsalparsaniya** [Vatsalparsaniya/ML_Knowledge#1]
Collect Machine Learning, Deep Learning, DataScience Concepts or Algorithms

- Ex. I want to Add `Concepts of Outlier` 
    - make a folder named `Outlier`, if already present in repository add additional information into that.
    - create `Readme.md` file in `Outlier` folder add your knowledge there
    - You can add knowledge like: 
      - Why this concept
      - How this algorithm works
      - Advantages
      - Disadvantages
      - What Are the Basic Assumption
      - In which problem statement you can your this concept or Algorithm
    - list of concepts: Stacking, Ensembling, Cross-Validation, Stacking VS Blending, standardisation, normalization, standardisation vs normalization, etc...
    - List of Algorithms: Linear Regression, Logistic Regression, Decision Tree, SVM (Support Vector Machine), Naive Bayes, KNN (K- Nearest Neighbors), K-Means, Random Forest, etc...

**Comment by pufuleterau** [comment]
Hello can I work on this project ?

**Comment by Vatsalparsaniya** [comment]
Yes, Follow the details I have mentioned in `Readme.md` file and contribute your work to this project.

**Comment by Vatsalparsaniya** [comment]
Hello contributors,
I have created **Web-Book** from your contribution **[https://vatsalparsaniya.github.io/ML_Knowledge/](https://vatsalparsaniya.github.io/ML_Knowledge/)** 
Thank you.
