### ISSUE TITLE
Algovis Python Library

### ISSUE THREAD

**Issue by tanviagwl98** [Vatsalparsaniya/ML_Knowledge#45]
I can share a script on **Algovis** python library that is used for visualizing and analyzing algorithms. In that there is visualization for bubble sort and quick sort that is a fun task and a great learning experience.
_If allowed I can create a Pull Request for the same._

**Comment by Vatsalparsaniya** [comment]
Yes, you can definitely contribute.

**Comment by tanviagwl98** [comment]
Thanks for letting me know, I have done the same.
