### ISSUE TITLE
Add Stacking Knowledge

### ISSUE THREAD

**Issue by Vatsalparsaniya** [Vatsalparsaniya/ML_Knowledge#6]
#1

**Comment by Erick-INCS** [comment]
Hi, I would like to help with this issue

**Comment by Erick-INCS** [comment]
@Vatsalparsaniya 
I noticed this repo does not participate in hacktoberfest, you need to add the "hactoberfest" topic 
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/classifying-your-repository-with-topics

**Comment by Vatsalparsaniya** [comment]
@Erick-INCS 
Thank you, for suggesting me to add the "hactoberfest" topic, but it is not necessary.
[https://hacktoberfest.digitalocean.com/details#details](https://hacktoberfest.digitalocean.com/details#details)
`Pull requests can be made in any GitHub-hosted repositories/projects. As long as the project is public and GitHub-hosted, your pull requests will count toward your participation.`

**Comment by Erick-INCS** [comment]
Oh okay, but this that I see in the hacktoberfest page

![Screenshot_20201003-211250~2.png](https://user-images.githubusercontent.com/57052867/95006840-69633800-05bd-11eb-985d-9cffd5adac62.png)

![Screenshot_20201003-211243~2.png](https://user-images.githubusercontent.com/57052867/95006842-6e27ec00-05bd-11eb-900b-e6ab478fb74c.png)

**Comment by Vatsalparsaniya** [comment]
Thank you @Erick-INCS I have added "hactoberfest" topic to this repository.

**Comment by Erick-INCS** [comment]
No problem :)
by the way, both have a typo haha "hactoberfest" -> "hacktoberfest"

**Comment by Vatsalparsaniya** [comment]
Hello contributors,
I have created **Web-Book** from your contribution **[https://vatsalparsaniya.github.io/ML_Knowledge/](https://vatsalparsaniya.github.io/ML_Knowledge/)** 
Thank you.

**Comment by Erick-INCS** [comment]
Awesome!
