### ISSUE TITLE
Add Ensembling Knowledge

### ISSUE THREAD

**Issue by Vatsalparsaniya** [Vatsalparsaniya/ML_Knowledge#7]
#1

**Comment by mohitsaha** [comment]
I have created a pull request please see it.

**Comment by ameez** [comment]
Simple way to understand model ensemble in Machine Learning is you can take example of a case where there are more than one models trained for one dataset but with different parameters.

let's say there are 3 models M1,M2,M3.

The predictions for above models are P1,P2,P3. 

So, we can take the average or the best prediction of the above model.

ex: Random Forest

**Comment by ameez** [comment]
Simple way to understand model ensemble in Machine Learning is you can take example of a case where there are more than one models trained for one dataset but with different parameters.

let's say there are 3 models M1,M2,M3.

The predictions for above models are P1,P2,P3.

So, we can take the average or the best prediction of the above model.

ex: Random Forest

**Comment by Vatsalparsaniya** [comment]
Hello contributors,
I have created **Web-Book** from your contribution **[https://vatsalparsaniya.github.io/ML_Knowledge/](https://vatsalparsaniya.github.io/ML_Knowledge/)** 
Thank you.
