### ISSUE TITLE
Add Cross-Validation Knowledge

### ISSUE THREAD

**Issue by Vatsalparsaniya** [Vatsalparsaniya/ML_Knowledge#8]
#1

**Comment by rijema** [comment]
Hey @Vatsalparsaniya , can I take this task?

**Comment by Vatsalparsaniya** [comment]
Yes

**Comment by rijema** [comment]
I am unable to change the Assignee's status, but I am already working on the task. Thanks!

**Comment by Vatsalparsaniya** [comment]
Now, I have assigned this task to you. :)

**Comment by rijema** [comment]
Thank you!

**Comment by Vatsalparsaniya** [comment]
You can also work on any Knowledge available in the repository like, `Outliers`, `Naive Bayes Classifier`, etc...

**Comment by rijema** [comment]
Nice! I will read about these techniques.

**Comment by rijema** [comment]
Nice! I will read about these techniques. I delivered a pull request few minutes ago about this issue

**Comment by MontyGhost** [comment]
I have updated the readme a little and created a pull request. How to merge this in the main branch?

**Comment by Vatsalparsaniya** [comment]
Great Work @MontyGhost, I have merged your contribution to the main branch.
Follow this [document](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request) for `How to merge pull request in the main branch?`

**Comment by MontyGhost** [comment]
Thank you @Vatsalparsaniya.

**Comment by simranswaraj** [comment]
Hey there!!! can i take this task?

**Comment by Vatsalparsaniya** [comment]
Yes, @simranswaraj

**Comment by Vatsalparsaniya** [comment]
Hello contributors,
I have created **Web-Book** from your contribution **[https://vatsalparsaniya.github.io/ML_Knowledge/](https://vatsalparsaniya.github.io/ML_Knowledge/)** 
Thank you.
