### ISSUE TITLE
Add standardisation, normalization, standardisation vs normalization Knowledge

### ISSUE THREAD

**Issue by Vatsalparsaniya** [Vatsalparsaniya/ML_Knowledge#9]
#1

**Comment by GauravPoosarla** [comment]
Is it the normalisation of data using standardisation and MinMax normalisation?

**Comment by swayam50** [comment]
Sorry, I sent a pull request before asking? This is my first time.

**Comment by Vatsalparsaniya** [comment]
Don't Worry, Hacktoberfest is for `Practice making your first pull request to a public repository before doing the real thing!`
But there are not any pull request form your side till now.

**Comment by swayam50** [comment]
I was confused a bit, I closed the other pull requests, finally sent one now.

**Comment by Vatsalparsaniya** [comment]
if you are finding any difficulties you can refer https://github.com/firstcontributions/first-contributions this repository

**Comment by Vatsalparsaniya** [comment]
Hello contributors,
I have created **Web-Book** from your contribution **[https://vatsalparsaniya.github.io/ML_Knowledge/](https://vatsalparsaniya.github.io/ML_Knowledge/)** 
Thank you.
